name: Deploy to Aliyun FCv3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 拉取代码
      - name: Checkout
        uses: actions/checkout@v3

      # 2️⃣ 安装 Python 并判断 requirements.txt
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies if requirements.txt exists
        run: |
          if [ -f "requirements.txt" ]; then
            pip install -r requirements.txt -t ./python_packages
          fi

      # 3️⃣ 打包 ZIP
      - name: Build zip package
        run: |
          mkdir package
          shopt -s extglob
          cp -r !(package|python_packages) package/
          if [ -d "python_packages" ]; then
            cp -r python_packages/* package/
          fi
          cd package
          zip -r ../function.zip .
          cd ..

      # 4️⃣ 安装新版 Aliyun CLI
      - name: Install Aliyun CLI
        run: |
          sudo /bin/bash -c "$(curl -fsSL https://aliyuncli.alicdn.com/install.sh)"
          aliyun version

      # 5️⃣ 配置阿里云 AK
      - name: Configure Aliyun
        run: |
          aliyun configure set \
            --region ${{ secrets.ALIYUN_REGION }} \
            --access-key-id ${{ secrets.ALIYUN_ACCESS_KEY_ID }} \
            --access-key-secret ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}

      # 6️⃣ 部署到 FCv3
      - name: Update FCv3 function
        run: |
          BASE64_CODE=$(base64 -w0 function.zip)
          aliyun fc PUT /2023-03-30/functions/page \
            --region ${{ secrets.ALIYUN_REGION }} \
            --form "code.zipFile=@function.zip"
            
